---
# Project path
:Project_Home: C:/Users/zhangkan/Documents/GitHub/ETLTester/unittest/itr2
# The max amount of sql returns.
:MAX_ROW: 200000
# How to connect database
:DBConnection:
  #	Database type: e.g. oracle, sqlserver, teradata... refer to ETLTester::Util::DBConnection::get_data_from_db
  :type: oracle
  #	Database address
  :address: ITR2ITG_DEDICATED
  #	User for login Database
  :user: infr
  #	Password for above user.
  :password: INFR_INFR_2011.bb
